name: Deploy DevOps Portal
  
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_TOKEN }}
    
    - name: Build and push backend
      uses: docker/build-push-action@v2
      with:
        context: ./backend
        push: true
        tags: your-username/devops-portal-backend:latest
    
    - name: Build and push frontend
      uses: docker/build-push-action@v2
      with:
        context: ./frontend
        push: true
        tags: your-username/devops-portal-frontend:latest
    
    - name: Deploy to Kubernetes
      uses: azure/k8s-deploy@v1
      if: github.ref == 'refs/heads/main'
      with:
        namespace: devops-portal
        manifests: infra/kubernetes/devops-portal.yaml
        images: |
          your-username/devops-portal-backend:latest
          your-username/devops-portal-frontend:latest
